config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :trip_details

  resources :tours

  get 'top/index'

  root to: "top#index"

end

app/models/tour.rb
class Tour
  include Mongoid::Document
  field :name, type: String
  field :description, type: String
  field :actions, type: Array
end

class Transfer
  attr_reader :name, :description, :method, :duration, :from, :to

  def initialize( name, desc, duration, method, from, to )
    @name = name
    @description = desc
    @method = method
    @duration = duration
    @from = from
    @to = to
  end

  def mongoize
    {
      :name          => name         ,
      :description   => description  ,
      :duration      => duration     ,
      :method        => method       ,
      :from          => from         ,
      :to            => to           ,
    }
  end

  class << self

    def demongoize( obj )
      Trasfer.new( obj[:name], obj[:description], obj[:duration], obj[:method], obj[:from], obj[:to] )
    end

    def mongoize( obj )
      case obj
      when Transfer then obj.mongoize
      else obj
      end
    end

    def evolve( obj )
      case obj
      when Trasfer then obj.mongoize
      else obj
      end
    end

  end
end

class Seeing
  attr_reader :name, :description, :duration, :spot

  def initialize( name, desc, duration, spot )
    @name = name
    @description = desc
    @duration = duration
    @spot = spot
  end

  def mongoize
    {
      :name        => name        ,
      :description => description ,
      :duration    => duration    ,
      :spot        => spot        ,
    }
  end

  class << self
    def demongoize( obj )
      Seeing.new( obj[:name], obj[:description], obj[:duration], obj[:spot] )
    end

    def mongoize( obj )
      case obj
      when Seeing then obj.mongoize
      else obj
      end
    end

    def evolve( obj )
      case obj
      when Seeing then obj.mongoize
      else obj
      end
    end
  end

end

app/models/trip_detail.rb
class TripDetail
  include Mongoid::Document
  field :trip_id, type: String
  field :index, type: Integer
  field :name, type: String
  field :description, type: String
  field :duration, type: Integer
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
def self.serialize_from_session(key, salt)
    record = to_adapter.get(key[0]["$oid"])
    record if record && record.authenticatable_salt == salt
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :set_tour, only: [:show, :edit, :update, :destroy]

  # GET /tours
  # GET /tours.json
  def index
    @tours = Tour.all
  end

  # GET /tours/1
  # GET /tours/1.json
  def show
  end

  # GET /tours/new
  def new
    @tour = Tour.new
  end

  # GET /tours/1/edit
  def edit
  end

  # POST /tours
  # POST /tours.json
  def create
    @tour = Tour.new(tour_params)

    respond_to do |format|
      if @tour.save
        format.html { redirect_to @tour, notice: 'Tour was successfully created.' }
        format.json { render :show, status: :created, location: @tour }
      else
        format.html { render :new }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tours/1
  # PATCH/PUT /tours/1.json
  def update
    respond_to do |format|
      if @tour.update(tour_params)
        format.html { redirect_to @tour, notice: 'Tour was successfully updated.' }
        format.json { render :show, status: :ok, location: @tour }
      else
        format.html { render :edit }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tours/1
  # DELETE /tours/1.json
  def destroy
    @tour.destroy
    respond_to do |format|
      format.html { redirect_to tours_url, notice: 'Tour was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tour
      @tour = Tour.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tour_params
      params.require(:tour).permit(:name, :description)
    end
end

app/controllers/trip_details_controller.rb
class TripDetailsController < ApplicationController
  before_action :set_trip_detail, only: [:show, :edit, :update, :destroy]

  # GET /trip_details
  # GET /trip_details.json
  def index
    @trip_details = TripDetail.all
  end

  # GET /trip_details/1
  # GET /trip_details/1.json
  def show
  end

  # GET /trip_details/new
  def new
    @trip_detail = TripDetail.new
  end

  # GET /trip_details/1/edit
  def edit
  end

  # POST /trip_details
  # POST /trip_details.json
  def create
    @trip_detail = TripDetail.new(trip_detail_params)

    respond_to do |format|
      if @trip_detail.save
        format.html { redirect_to @trip_detail, notice: 'Trip detail was successfully created.' }
        format.json { render :show, status: :created, location: @trip_detail }
      else
        format.html { render :new }
        format.json { render json: @trip_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trip_details/1
  # PATCH/PUT /trip_details/1.json
  def update
    respond_to do |format|
      if @trip_detail.update(trip_detail_params)
        format.html { redirect_to @trip_detail, notice: 'Trip detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @trip_detail }
      else
        format.html { render :edit }
        format.json { render json: @trip_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trip_details/1
  # DELETE /trip_details/1.json
  def destroy
    @trip_detail.destroy
    respond_to do |format|
      format.html { redirect_to trip_details_url, notice: 'Trip detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip_detail
      @trip_detail = TripDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_detail_params
      params.require(:trip_detail).permit(:trip_id, :index, :name, :description, :duration)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/helpers/trip_details_helper.rb
module TripDetailsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Otavy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag :modernizr %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="row navbar" id="nav1">
  <!-- Toggle for mobile navigation, targeting the <ul> -->
  <a class="toggle" gumby-trigger="#nav1 > ul" href="#"><i class="icon-menu"></i></a>
  <h2 class="four columns logo"><a href="#">Otavy</a></h2>
  <ul class="eight columns">
    <li><a href="#">Trips</a></li>
    <li>
      <a href="#">New Trip</a>
      <div class="dropdown">
        <ul>
          <li><a href="#">The Grid</a></li>
          <li><a href="#">UI Kit</a></li>
          <li><a href="#">Sass</a></li>
          <li><a href="#">JavaScript</a></li>
          <li><a href="#">Demo</a></li>
        </ul>
      </div>
    </li>
    <li><a href="#">Customize</a></li>
  </ul>
</div>
<div class="row">
<div class="centered twelve column">
<p>Login Status</p>
<% if user_signed_in? %>
  <p>Logged in as <strong><%= current_user.email %></strong>.</p>
  <%= link_to 'Change profile', edit_user_registration_path %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
<% else %>
  <p>Not logged on, Please login.</p>
  <%= link_to "Sign-in", new_user_registration_path %> |
  <%= link_to "Login", new_user_session_path %>
<% end %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
</div>
</div>
<%= yield %>

</body>
</html>

app/views/top/index.html.erb
<div class="row" style="margin-top: 5%">
<div class="centered six columns" style='text-align: center'>
<h1>Otavy</h1>
<p style='text-align: center'>Best assistant for your trip</p>
<ul style="text-align: center; margin-top: 5%">
<li class="append field">
    <input class="wide email input" type="email" placeholder="Your Email Address" />
</li>
<li class="append field">
    <input class="wide input" type="password" placeholder="Your Password" />
</li>
</ul>
<div class="medium default btn"><input type="submit" value="Login" /></div>
</div>
</div>

app/views/tours/_form.html.erb
<%= form_for(@tour) do |f| %>
  <% if @tour.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tour.errors.count, "error") %> prohibited this tour from being saved:</h2>

      <ul>
      <% @tour.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tours/edit.html.erb
<h1>Editing tour</h1>

<%= render 'form' %>

<%= link_to 'Show', @tour %> |
<%= link_to 'Back', tours_path %>

app/views/tours/index.html.erb
<h1>Listing tours</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tours.each do |tour| %>
      <tr>
        <td><%= tour.name %></td>
        <td><%= tour.description %></td>
        <td><%= link_to 'Show', tour %></td>
        <td><%= link_to 'Edit', edit_tour_path(tour) %></td>
        <td><%= link_to 'Destroy', tour, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tour', new_tour_path %>

app/views/tours/new.html.erb
<div class="row">
<div class="centered six columns">
<h2>Create New Trip</h2>
<%= render 'form' %>
<%= link_to 'Back', tours_path %>
</div>
</div>

app/views/tours/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tour.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @tour.description %>
</p>

<%= link_to 'Edit', edit_tour_path(@tour) %> |
<%= link_to 'Back', tours_path %>

app/views/trip_details/_form.html.erb
<%= form_for(@trip_detail) do |f| %>
  <% if @trip_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trip_detail.errors.count, "error") %> prohibited this trip_detail from being saved:</h2>

      <ul>
      <% @trip_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :trip_id %><br>
    <%= f.text_field :trip_id %>
  </div>
  <div class="field">
    <%= f.label :index %><br>
    <%= f.number_field :index %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :duration %><br>
    <%= f.number_field :duration %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trip_details/edit.html.erb
<h1>Editing trip_detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @trip_detail %> |
<%= link_to 'Back', trip_details_path %>

app/views/trip_details/index.html.erb
<h1>Listing trip_details</h1>

<table>
  <thead>
    <tr>
      <th>Trip</th>
      <th>Index</th>
      <th>Name</th>
      <th>Description</th>
      <th>Duration</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trip_details.each do |trip_detail| %>
      <tr>
        <td><%= trip_detail.trip_id %></td>
        <td><%= trip_detail.index %></td>
        <td><%= trip_detail.name %></td>
        <td><%= trip_detail.description %></td>
        <td><%= trip_detail.duration %></td>
        <td><%= link_to 'Show', trip_detail %></td>
        <td><%= link_to 'Edit', edit_trip_detail_path(trip_detail) %></td>
        <td><%= link_to 'Destroy', trip_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trip detail', new_trip_detail_path %>

app/views/trip_details/new.html.erb
<h1>New trip_detail</h1>

<%= render 'form' %>

<%= link_to 'Back', trip_details_path %>

app/views/trip_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Trip:</strong>
  <%= @trip_detail.trip_id %>
</p>

<p>
  <strong>Index:</strong>
  <%= @trip_detail.index %>
</p>

<p>
  <strong>Name:</strong>
  <%= @trip_detail.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @trip_detail.description %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @trip_detail.duration %>
</p>

<%= link_to 'Edit', edit_trip_detail_path(@trip_detail) %> |
<%= link_to 'Back', trip_details_path %>